### ISSUE TITLE
PSGI extension for interaction with monitoring

### ISSUE THREAD

**Issue by robrwo** [plack/psgi-specs#43]
I am working on some middleware that sends data to statsd, and would like to suggest using the key `psgix.monitor.statsd' for a statsd client that supports some standard methods.

**Comment by robrwo** [comment]
The module [Plack::Middleware::Statsd](https://metacpan.org/pod/Plack::Middleware::Statsd) sets/uses the `psgix.monitor.statsd`key, which is also used by [Catalyst::Plugin::Statsd](https://metacpan.org/release/Catalyst-Plugin-Statsd).

It is expected that the object would support the common methods that Net::Statsd::Client or Net::Statsd::Tiny do:
- increment
- decrement
- timing_ms
- set_add
- gauge

**Comment by miyagawa** [comment]
psgix namespace is used for extensions shared by multiple PSGI server implementations.

The use case doesn't seem to require the psgix namespace, you can rather implement in your own namespace.
